### ISSUE TITLE
Supporting more types in Boyer-Moore

### ISSUE THREAD

**Issue by data-man** [ziglibs/string-searching#1]
Currently this library only supports `u8`.
Feature request: support any type.

**Comment by joachimschmidt557** [comment]
Yup, this is definitely a feature worth having. However, arbitrary types can't be supported as all possible elements of the type (in the case of `u8` there are 256 possible elements) need to be known in order to add them to the bad character table.

**Comment by joachimschmidt557** [comment]
I'd suggest supporting all integer (signed and unsigned, or maybe just unsigned?) types.

**Comment by data-man** [comment]
Oh, sorry! I forgot about the limitations of the algorithm. :(
Knuth–Morris–Pratt algorithm is more suitable for any type.

Just an idea: rename this repository to zig-search-algorithms or something like this.
And add other popular algorithms.

**Comment by data-man** [comment]
There is awesome [String Matching Algorithms Research Tool](https://github.com/smart-tool/smart) but it is GPL-licensed.

**Comment by joachimschmidt557** [comment]
Yup, I'll make another issue for adding more algorithms.

**Comment by data-man** [comment]
I think new name `zig-string-searching` is slightly incorrect now. :)
I suggest use `zig-pattern-searching`.

**Comment by joachimschmidt557** [comment]
Hmm, `pattern` kind of implies some regex-ish matching. According to [Wikipedia](https://en.wikipedia.org/wiki/String-searching_algorithm), "string-searching algorithm" is the term for this family of algorithms.

**Comment by data-man** [comment]
Sure, but structs are't strings (if new algorithms are added).

**Comment by joachimschmidt557** [comment]
I think that we want to limit the scope of this repository to slices of some type `T`, i.e. searching for a `[]const T` in another `[]const T`. This is basically equivalent to the mathematical definition of strings, which are finite sequences of symbols from an alphabet. The alphabet would be `T` in this case.

This does not prevent us from choosing some struct for `T`. We would have to include some equality function in that case because structs cannot be compared with the `==` operator anymore.

For example:

```zig
const Abc = struct {
    id: usize,
    some_data: []const u8,

    pub fn equals(self: Abc, other: Abc) bool {
        return self.id == other.id;
    }
};
```

We can then search for a `[]const Abc` in a `[]const Abc` if we want to.

**Comment by data-man** [comment]
`std.meta.trait.isIndexable` now supports vectors.
So potentially, some algorithms could use this trait.
But I'm waiting when https://github.com/ziglang/zig/pull/5443 will be merged.

**Comment by joachimschmidt557** [comment]
Hmm okay, support for types that follow 2 rules can be added:

- indexable
- length can be queried

That would include slices as well as vectors, I suppose.

**Comment by joachimschmidt557** [comment]
Implemented in https://github.com/ziglibs/zig-string-searching/commit/15a7ec28db274b1fce12ff7cb42a757e03808626
